version: '3.5'
services:

  # docker-compose exec sqldb mysql -ukimaiuser -pkimaipassword kimai
  sqldb:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=kimai
      - MYSQL_USER=kimaiuser
      - MYSQL_PASSWORD=kimaipassword
      - MYSQL_ROOT_PASSWORD=changemeplease
    volumes:
      - mysql:/var/lib/mysql
    command: --default-storage-engine innodb
    restart: unless-stopped
    ports:
      - 5306:3306

  kimai:
    image: kimai/kimai2:apache-dev
    environment:
      - ADMINMAIL=admin@kimai.local
      - ADMINPASS=changemeplease
      - DATABASE_URL=mysql://kimaiuser:kimaipassword@sqldb/kimai
      - TRUSTED_HOSTS=nginx,localhost,127.0.0.1,kimai.test
    ports:
      - 8001:8001
    volumes:
      - ./BrowserPluginBundle:/opt/kimai/var/plugins/BrowserPluginBundle
      - ./docker-vols/CustomCSSBundle-1.3:/opt/kimai/var/plugins/CustomCSSBundle
      - ./docker-vols/config:/opt/kimai/config
      - ./docker-vols/public:/opt/kimai/public
      - ./docker-vols/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      # - ./ldap.conf:/etc/openldap/ldap.conf:z
      # - ./ROOT-CA.pem:/etc/ssl/certs/ROOT-CA.pem:z
    restart: unless-stopped
    healthcheck:
      disable: true

  postfix:
    image: catatnight/postfix:latest
    environment:
      maildomain: neontribe.co.uk
      smtp_user: kimai:kimai
    restart: unless-stopped

volumes:
    var:
    public:
    mysql:
