services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:

    KimaiPlugin\BrowserPluginBundle\:
        resource: '../../*'
        exclude: '../../{Resources}'

    browser_plugin_response_lister:
        class: KimaiPlugin\BrowserPluginBundle\Listener\ResponseListener
        arguments: ['@logger']
        tags:
            - {
                name: kernel.event_listener,
                event: kernel.response,
                method: onKernelResponse,
              }